#pragma once
#include "Render.hpp"

typedef struct _RGBA
{
    FLOAT R;
    FLOAT G;
    FLOAT B;
    FLOAT A;

}RGBA, * PRGBA;

EXTERN_C __MIDL_DECLSPEC_DLLEXPORT BOOL WINAPI LoadRender(LPCWSTR WinName, LPCWSTR ClsName, PVOID Callback, UINT UsePresent, FLOAT ThickNess, PHANDLE hWnd, PHANDLE hThread);
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT BOOL WINAPI UnLoadRender();
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI MessageLoop();
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI SetSwitch();
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT FLOAT WINAPI GetFPS();
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI DrawRect(FLOAT X, FLOAT Y, FLOAT W, FLOAT H, PRGBA Color, FLOAT ThickNess);
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI DrawLine(FLOAT X1, FLOAT Y1, FLOAT X2, FLOAT Y2, PRGBA Color, FLOAT ThickNess);
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI DrawCircle(FLOAT X, FLOAT Y, FLOAT Radius, PRGBA Color, INT Segments, FLOAT ThickNess);
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI DrawString(FLOAT X, FLOAT Y, PRGBA Color, LPCSTR Str);
EXTERN_C __MIDL_DECLSPEC_DLLEXPORT VOID WINAPI DrawFilledRect(FLOAT X, FLOAT Y, FLOAT W, FLOAT H, PRGBA Color);
